name: Storybook-Build-Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn Install
        run: yarn
      - name: Storybook Build
        run: yarn build-storybook
